# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel:
        container_name: "laravel_pdf"
        build:
            context: ./vendor/laravel/sail/runtimes/8.0
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.0/app
        ports:
            - '80:80'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
    gotenberg:
        container_name: "gotenberg_pdf"
        image: gotenberg/gotenberg
        ports:
            - '2000:3000'
        networks:
            - sail
    puppeteer:
        container_name: "puppeteer_pdf"
        build:
            context: ./../pdf-rendering-srv
            dockerfile: Dockerfile
        volumes:
            - './puppeteer:/home/node/srv/files'
        ports:
            - '2001:9000'
            - '2002:9222'
        networks:
            - sail
    nextjs:
        container_name: "nextjs_pdf"
        image: node:15
        command: tail -F /app/README.md
        ports:
            - "8080:3000"
        depends_on:
            - laravel
        volumes:
            - ./../nextjs/:/app/
        networks:
            - sail
networks:
    sail:
        driver: bridge
